<?php

namespace Database\Seeders\Geocodes;

use Illuminate\Database\Seeder;
use App\Models\Geocodes\Country;
use DB;
/**
 * Class CountryTableSeeder.
 */
class CountrySeeder extends Seeder
{

    /**
     * Run the database seed.
     */
    public function run(): void
    {

        DB::table('countries')->delete();

        $countries = array(

        	// Records 01-99 (Afghanistan to India)

            array('flag'=>urlFlag('af'),'code' => 'AF','name' => trans('modules/geocodes/countries/seeders.Afghanistan'), 'code2' => 'AFG', 'numcode' => '4', 'phone_code' => '+93'),
            array('flag'=>urlFlag('a'),'code' => 'AL', 'name' => trans('modules/geocodes/countries/seeders.Albania'), 'code2' => 'ALB', 'numcode' => '8', 'phone_code' => '+355'),
            array('flag'=>urlFlag('dz'),'code' => 'DZ', 'name' => trans('modules/geocodes/countries/seeders.Algeria'), 'code2' => 'DZA', 'numcode' => '12', 'phone_code' => '+213'),
            array('flag'=>urlFlag('as'),'code' => 'AS','name' => trans('modules/geocodes/countries/seeders.American Samoa'), 'code2' => 'ASM', 'numcode' => '16', 'phone_code' => '+1684'),
            array('flag'=>urlFlag('ad'),'code' => 'AD', 'name' => trans('modules/geocodes/countries/seeders.Andorra'), 'code2' => 'AND', 'numcode' => '20', 'phone_code' => '+376'),
            array('flag'=>urlFlag('ao'),'code' => 'AO', 'name' => trans('modules/geocodes/countries/seeders.Angola'), 'code2' => 'AGO', 'numcode' => '24', 'phone_code' => '+244'),
            array('flag'=>urlFlag('ai'),'code' => 'AI', 'name' => trans('modules/geocodes/countries/seeders.Anguilla'), 'code2' => 'AIA', 'numcode' => '660', 'phone_code' => '+1264'),
            array('flag'=>urlFlag('aq'),'code' => 'AQ', 'name' => trans('modules/geocodes/countries/seeders.Antarctica'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+0'),
            array('flag'=>urlFlag('ag'),'code' => 'AG', 'name' => trans('modules/geocodes/countries/seeders.Antigua and Barbuda'), 'code2' => 'ATG', 'numcode' => '28', 'phone_code' => '+1268'),
            array('flag'=>urlFlag('ar'),'code' => 'AR', 'name' => trans('modules/geocodes/countries/seeders.Argentina'), 'code2' => 'ARG', 'numcode' => '32', 'phone_code' => '+54'),
            array('flag'=>urlFlag('am'),'code' => 'AM', 'name' => trans('modules/geocodes/countries/seeders.Armenia'), 'code2' => 'ARM', 'numcode' => '51', 'phone_code' => '+374'),
            array('flag'=>urlFlag('aw'),'code' => 'AW', 'name' => trans('modules/geocodes/countries/seeders.Aruba'), 'code2' => 'ABW', 'numcode' => '533', 'phone_code' => '+297'),
            array('flag'=>urlFlag('au'),'code' => 'AU', 'name' => trans('modules/geocodes/countries/seeders.Australia'), 'code2' => 'AUS', 'numcode' => '36', 'phone_code' => '+61'),
            array('flag'=>urlFlag('at'),'code' => 'AT', 'name' => trans('modules/geocodes/countries/seeders.Austria'), 'code2' => 'AUT', 'numcode' => '40', 'phone_code' => '+43'),
            array('flag'=>urlFlag('az'),'code' => 'AZ', 'name' => trans('modules/geocodes/countries/seeders.Azerbaijan'), 'code2' => 'AZE', 'numcode' => '31', 'phone_code' => '+994'),
            array('flag'=>urlFlag('bs'),'code' => 'BS', 'name' => trans('modules/geocodes/countries/seeders.Bahamas'), 'code2' => 'BHS', 'numcode' => '44', 'phone_code' => '+1242'),
            array('flag'=>urlFlag('bh'),'code' => 'BH', 'name' => trans('modules/geocodes/countries/seeders.Bahrain'), 'code2' => 'BHR', 'numcode' => '48', 'phone_code' => '+973'),
            array('flag'=>urlFlag('bd'),'code' => 'BD', 'name' => trans('modules/geocodes/countries/seeders.Bangladesh'), 'code2' => 'BGD', 'numcode' => '50', 'phone_code' => '+880'),
            array('flag'=>urlFlag('bb'),'code' => 'BB', 'name' => trans('modules/geocodes/countries/seeders.Barbados'), 'code2' => 'BRB', 'numcode' => '52', 'phone_code' => '+1246'),
            array('flag'=>urlFlag('by'),'code' => 'BY', 'name' => trans('modules/geocodes/countries/seeders.Belarus'), 'code2' => 'BLR', 'numcode' => '112', 'phone_code' => '+375'),
            array('flag'=>urlFlag('be'),'code' => 'BE', 'name' => trans('modules/geocodes/countries/seeders.Belgium'), 'code2' => 'BEL', 'numcode' => '56', 'phone_code' => '+32'),
            array('flag'=>urlFlag('bz'),'code' => 'BZ', 'name' => trans('modules/geocodes/countries/seeders.Belize'), 'code2' => 'BLZ', 'numcode' => '84', 'phone_code' => '+501'),
            array('flag'=>urlFlag('bj'),'code' => 'BJ', 'name' => trans('modules/geocodes/countries/seeders.Benin'), 'code2' => 'BEN', 'numcode' => '204', 'phone_code' => '+229'),
            array('flag'=>urlFlag('bm'),'code' => 'BM', 'name' => trans('modules/geocodes/countries/seeders.Bermuda'), 'code2' => 'BMU', 'numcode' => '60', 'phone_code' => '+1441'),
            array('flag'=>urlFlag('bt'),'code' => 'BT', 'name' => trans('modules/geocodes/countries/seeders.Bhutan'), 'code2' => 'BTN', 'numcode' => '64', 'phone_code' => '+975'),
            array('flag'=>urlFlag('bo'),'code' => 'BO', 'name' => trans('modules/geocodes/countries/seeders.Bolivia'), 'code2' => 'BOL', 'numcode' => '68', 'phone_code' => '+591'),
            array('flag'=>urlFlag('ba'),'code' => 'BA', 'name' => trans('modules/geocodes/countries/seeders.Bosnia and Herzegovina'), 'code2' => 'BIH', 'numcode' => '70', 'phone_code' => '+387'),
            array('flag'=>urlFlag('bw'),'code' => 'BW', 'name' => trans('modules/geocodes/countries/seeders.Botswana'), 'code2' => 'BWA', 'numcode' => '72', 'phone_code' => '+267'),
            array('flag'=>urlFlag('bv'),'code' => 'BV', 'name' => trans('modules/geocodes/countries/seeders.Bouvet Island'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+0'),
            array('flag'=>urlFlag('br'),'code' => 'BR', 'name' => trans('modules/geocodes/countries/seeders.Brazil'), 'code2' => 'BRA', 'numcode' => '76', 'phone_code' => '+55'),
            array('flag'=>urlFlag('io'),'code' => 'IO', 'name' => trans('modules/geocodes/countries/seeders.British Indian Ocean Territory'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+246'),
            array('flag'=>urlFlag('bn'),'code' => 'BN', 'name' => trans('modules/geocodes/countries/seeders.Brunei Darussalam'), 'code2' => 'BRN', 'numcode' => '96', 'phone_code' => '+673'),
            array('flag'=>urlFlag('bg'),'code' => 'BG', 'name' => trans('modules/geocodes/countries/seeders.Bulgaria'), 'code2' => 'BGR', 'numcode' => '100', 'phone_code' => '+359'),
            array('flag'=>urlFlag('bf'),'code' => 'BF', 'name' => trans('modules/geocodes/countries/seeders.Burkina Faso'), 'code2' => 'BFA', 'numcode' => '854', 'phone_code' => '+226'),
            array('flag'=>urlFlag('bi'),'code' => 'BI', 'name' => trans('modules/geocodes/countries/seeders.Burundi'), 'code2' => 'BDI', 'numcode' => '108', 'phone_code' => '+257'),
            array('flag'=>urlFlag('kh'),'code' => 'KH', 'name' => trans('modules/geocodes/countries/seeders.Cambodia'), 'code2' => 'KHM', 'numcode' => '116', 'phone_code' => '+855'),
            array('flag'=>urlFlag('cm'),'code' => 'CM', 'name' => trans('modules/geocodes/countries/seeders.Cameroon'), 'code2' => 'CMR', 'numcode' => '120', 'phone_code' => '+237'),
            array('flag'=>urlFlag('ca'),'code' => 'CA', 'name' => trans('modules/geocodes/countries/seeders.Canada'), 'code2' => 'CAN', 'numcode' => '124', 'phone_code' => '+1'),
            array('flag'=>urlFlag('cv'),'code' => 'CV', 'name' => trans('modules/geocodes/countries/seeders.Cape Verde'), 'code2' => 'CPV', 'numcode' => '132', 'phone_code' => '+238'),
            array('flag'=>urlFlag('ky'),'code' => 'KY', 'name' => trans('modules/geocodes/countries/seeders.Cayman Islands'), 'code2' => 'CYM', 'numcode' => '136', 'phone_code' => '+1345'),
            array('flag'=>urlFlag('cf'),'code' => 'CF', 'name' => trans('modules/geocodes/countries/seeders.Central African Republic'), 'code2' => 'CAF', 'numcode' => '140', 'phone_code' => '+236'),
            array('flag'=>urlFlag('td'),'code' => 'TD', 'name' => trans('modules/geocodes/countries/seeders.Chad'), 'code2' => 'TCD', 'numcode' => '148', 'phone_code' => '+235'),
            array('flag'=>urlFlag('cl'),'code' => 'CL', 'name' => trans('modules/geocodes/countries/seeders.Chile'), 'code2' => 'CHL', 'numcode' => '152', 'phone_code' => '+56'),
            array('flag'=>urlFlag('cn'),'code' => 'CN', 'name' => trans('modules/geocodes/countries/seeders.China'), 'code2' => 'CHN', 'numcode' => '156', 'phone_code' => '+86'),
            array('flag'=>urlFlag('cx'),'code' => 'CX', 'name' => trans('modules/geocodes/countries/seeders.Christmas Island'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+61'),
            array('flag'=>urlFlag('cc'),'code' => 'CC', 'name' => trans('modules/geocodes/countries/seeders.Cocos (Keeling) Islands'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+672'),
            array('flag'=>urlFlag('co'),'code' => 'CO', 'name' => trans('modules/geocodes/countries/seeders.Colombia'), 'code2' => 'COL', 'numcode' => '170', 'phone_code' => '+57'),
            array('flag'=>urlFlag('km'),'code' => 'KM', 'name' => trans('modules/geocodes/countries/seeders.Comoros'), 'code2' => 'COM', 'numcode' => '174', 'phone_code' => '+269'),
            array('flag'=>urlFlag('cg'),'code' => 'CG', 'name' => trans('modules/geocodes/countries/seeders.Congo'), 'code2' => 'COG', 'numcode' => '178', 'phone_code' => '+242'),
            array('flag'=>urlFlag('cd'),'code' => 'CD', 'name' => trans('modules/geocodes/countries/seeders.Congo, the Democratic Republic of the'), 'code2' => 'COD', 'numcode' => '180', 'phone_code' => '+242'),
            array('flag'=>urlFlag('ck'),'code' => 'CK', 'name' => trans('modules/geocodes/countries/seeders.Cook Islands'), 'code2' => 'COK', 'numcode' => '184', 'phone_code' => '+682'),
            array('flag'=>urlFlag('cr'),'code' => 'CR', 'name' => trans('modules/geocodes/countries/seeders.Costa Rica'), 'code2' => 'CRI', 'numcode' => '188', 'phone_code' => '+506'),
            array('flag'=>urlFlag('ci'),'code' => 'CI', 'name' => trans('modules/geocodes/countries/seeders.Cote D\'Ivoire'), 'code2' => 'CIV', 'numcode' => '384', 'phone_code' => '+225'),
            array('flag'=>urlFlag('hr'),'code' => 'HR', 'name' => trans('modules/geocodes/countries/seeders.Croatia'), 'code2' => 'HRV', 'numcode' => '191', 'phone_code' => '+385'),
            array('flag'=>urlFlag('cu'),'code' => 'CU', 'name' => trans('modules/geocodes/countries/seeders.Cuba'), 'code2' => 'CUB', 'numcode' => '192', 'phone_code' => '+53'),
            array('flag'=>urlFlag('cy'),'code' => 'CY', 'name' => trans('modules/geocodes/countries/seeders.Cyprus'), 'code2' => 'CYP', 'numcode' => '196', 'phone_code' => '+357'),
            array('flag'=>urlFlag('cz'),'code' => 'CZ', 'name' => trans('modules/geocodes/countries/seeders.Czech Republic'), 'code2' => 'CZE', 'numcode' => '203', 'phone_code' => '+420'),
            array('flag'=>urlFlag('dk'),'code' => 'DK', 'name' => trans('modules/geocodes/countries/seeders.Denmark'), 'code2' => 'DNK', 'numcode' => '208', 'phone_code' => '+45'),
            array('flag'=>urlFlag('dj'),'code' => 'DJ', 'name' => trans('modules/geocodes/countries/seeders.Djibouti'), 'code2' => 'DJI', 'numcode' => '262', 'phone_code' => '+253'),
            array('flag'=>urlFlag('dm'),'code' => 'DM', 'name' => trans('modules/geocodes/countries/seeders.Dominica'), 'code2' => 'DMA', 'numcode' => '212', 'phone_code' => '+1767'),
            array('flag'=>urlFlag('do'),'code' => 'DO', 'name' => trans('modules/geocodes/countries/seeders.Dominican Republic'), 'code2' => 'DOM', 'numcode' => '214', 'phone_code' => '+1809'),
            array('flag'=>urlFlag('ec'),'code' => 'EC', 'name' => trans('modules/geocodes/countries/seeders.Ecuador'), 'code2' => 'ECU', 'numcode' => '218', 'phone_code' => '+593'),
            array('flag'=>urlFlag('eg'),'code' => 'EG', 'name' => trans('modules/geocodes/countries/seeders.Egypt'), 'code2' => 'EGY', 'numcode' => '818', 'phone_code' => '+20'),
            array('flag'=>urlFlag('sv'),'code' => 'SV', 'name' => trans('modules/geocodes/countries/seeders.El Salvador'), 'code2' => 'SLV', 'numcode' => '222', 'phone_code' => '+503'),
            array('flag'=>urlFlag('gq'),'code' => 'GQ', 'name' => trans('modules/geocodes/countries/seeders.Equatorial Guinea'), 'code2' => 'GNQ', 'numcode' => '226', 'phone_code' => '+240'),
            array('flag'=>urlFlag('er'),'code' => 'ER', 'name' => trans('modules/geocodes/countries/seeders.Eritrea'), 'code2' => 'ERI', 'numcode' => '232', 'phone_code' => '+291'),
            array('flag'=>urlFlag('ee'),'code' => 'EE', 'name' => trans('modules/geocodes/countries/seeders.Estonia'), 'code2' => 'EST', 'numcode' => '233', 'phone_code' => '+372'),
            array('flag'=>urlFlag('et'),'code' => 'ET', 'name' => trans('modules/geocodes/countries/seeders.Ethiopia'), 'code2' => 'ETH', 'numcode' => '231', 'phone_code' => '+251'),
            array('flag'=>urlFlag('fk'),'code' => 'FK', 'name' => trans('modules/geocodes/countries/seeders.Falkland Islands (Malvinas)'), 'code2' => 'FLK', 'numcode' => '238', 'phone_code' => '+500'),
            array('flag'=>urlFlag('fo'),'code' => 'FO', 'name' => trans('modules/geocodes/countries/seeders.Faroe Islands'), 'code2' => 'FRO', 'numcode' => '234', 'phone_code' => '+298'),
            array('flag'=>urlFlag('fj'),'code' => 'FJ', 'name' => trans('modules/geocodes/countries/seeders.Fiji'), 'code2' => 'FJI', 'numcode' => '242', 'phone_code' => '+679'),
            array('flag'=>urlFlag('fi'),'code' => 'FI', 'name' => trans('modules/geocodes/countries/seeders.Finland'), 'code2' => 'FIN', 'numcode' => '246', 'phone_code' => '+358'),
            array('flag'=>urlFlag('fr'),'code' => 'FR', 'name' => trans('modules/geocodes/countries/seeders.France'), 'code2' => 'FRA', 'numcode' => '250', 'phone_code' => '+33'),
            array('flag'=>urlFlag('gf'),'code' => 'GF', 'name' => trans('modules/geocodes/countries/seeders.French Guiana'), 'code2' => 'GUF', 'numcode' => '254', 'phone_code' => '+594'),
            array('flag'=>urlFlag('pf'),'code' => 'PF', 'name' => trans('modules/geocodes/countries/seeders.French Polynesia'), 'code2' => 'PYF', 'numcode' => '258', 'phone_code' => '+689'),
            array('flag'=>urlFlag('tf'),'code' => 'TF', 'name' => trans('modules/geocodes/countries/seeders.French Southern Territories'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+0'),
            array('flag'=>urlFlag('ga'),'code' => 'GA', 'name' => trans('modules/geocodes/countries/seeders.Gabon'), 'code2' => 'GAB', 'numcode' => '266', 'phone_code' => '+241'),
            array('flag'=>urlFlag('gm'),'code' => 'GM', 'name' => trans('modules/geocodes/countries/seeders.Gambia'), 'code2' => 'GMB', 'numcode' => '270', 'phone_code' => '+220'),
            array('flag'=>urlFlag('ge'),'code' => 'GE', 'name' => trans('modules/geocodes/countries/seeders.Georgia'), 'code2' => 'GEO', 'numcode' => '268', 'phone_code' => '+995'),
            array('flag'=>urlFlag('de'),'code' => 'DE', 'name' => trans('modules/geocodes/countries/seeders.Germany'), 'code2' => 'DEU', 'numcode' => '276', 'phone_code' => '+49'),
            array('flag'=>urlFlag('gh'),'code' => 'GH', 'name' => trans('modules/geocodes/countries/seeders.Ghana'), 'code2' => 'GHA', 'numcode' => '288', 'phone_code' => '+233'),
            array('flag'=>urlFlag('gi'),'code' => 'GI', 'name' => trans('modules/geocodes/countries/seeders.Gibraltar'), 'code2' => 'GIB', 'numcode' => '292', 'phone_code' => '+350'),
            array('flag'=>urlFlag('gr'),'code' => 'GR', 'name' => trans('modules/geocodes/countries/seeders.Greece'), 'code2' => 'GRC', 'numcode' => '300', 'phone_code' => '+30'),
            array('flag'=>urlFlag('gl'),'code' => 'GL', 'name' => trans('modules/geocodes/countries/seeders.Greenland'), 'code2' => 'GRL', 'numcode' => '304', 'phone_code' => '+299'),
            array('flag'=>urlFlag('gd'),'code' => 'GD', 'name' => trans('modules/geocodes/countries/seeders.Grenada'), 'code2' => 'GRD', 'numcode' => '308', 'phone_code' => '+1473'),
            array('flag'=>urlFlag('gp'),'code' => 'GP', 'name' => trans('modules/geocodes/countries/seeders.Guadeloupe'), 'code2' => 'GLP', 'numcode' => '312', 'phone_code' => '+590'),
            array('flag'=>urlFlag('gu'),'code' => 'GU', 'name' => trans('modules/geocodes/countries/seeders.Guam'), 'code2' => 'GUM', 'numcode' => '316', 'phone_code' => '+1671'),
            array('flag'=>urlFlag('gt'),'code' => 'GT', 'name' => trans('modules/geocodes/countries/seeders.Guatemala'), 'code2' => 'GTM', 'numcode' => '320', 'phone_code' => '+502'),
            array('flag'=>urlFlag('gn'),'code' => 'GN', 'name' => trans('modules/geocodes/countries/seeders.Guinea'), 'code2' => 'GIN', 'numcode' => '324', 'phone_code' => '+224'),
            array('flag'=>urlFlag('gw'),'code' => 'GW', 'name' => trans('modules/geocodes/countries/seeders.Guinea-Bissau'), 'code2' => 'GNB', 'numcode' => '624', 'phone_code' => '+245'),
            array('flag'=>urlFlag('gy'),'code' => 'GY', 'name' => trans('modules/geocodes/countries/seeders.Guyana'), 'code2' => 'GUY', 'numcode' => '328', 'phone_code' => '+592'),
            array('flag'=>urlFlag('ht'),'code' => 'HT', 'name' => trans('modules/geocodes/countries/seeders.Haiti'), 'code2' => 'HTI', 'numcode' => '332', 'phone_code' => '+509'),
            array('flag'=>urlFlag('hm'),'code' => 'HM', 'name' => trans('modules/geocodes/countries/seeders.Heard Island and Mcdonald Islands'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+0'),
            array('flag'=>urlFlag('va'),'code' => 'VA', 'name' => trans('modules/geocodes/countries/seeders.Holy See (Vatican City State)'), 'code2' => 'VAT', 'numcode' => '336', 'phone_code' => '+39'),
            array('flag'=>urlFlag('hn'),'code' => 'HN', 'name' => trans('modules/geocodes/countries/seeders.Honduras'), 'code2' => 'HND', 'numcode' => '340', 'phone_code' => '+504'),
            array('flag'=>urlFlag('hk'),'code' => 'HK', 'name' => trans('modules/geocodes/countries/seeders.Hong Kong'), 'code2' => 'HKG', 'numcode' => '344', 'phone_code' => '+852'),
            array('flag'=>urlFlag('hu'),'code' => 'HU', 'name' => trans('modules/geocodes/countries/seeders.Hungary'), 'code2' => 'HUN', 'numcode' => '348', 'phone_code' => '+36'),
            array('flag'=>urlFlag('is'),'code' => 'IS', 'name' => trans('modules/geocodes/countries/seeders.Iceland'), 'code2' => 'ISL', 'numcode' => '352', 'phone_code' => '+354'),
            array('flag'=>urlFlag('in'),'code' => 'IN', 'name' => trans('modules/geocodes/countries/seeders.India'), 'code2' => 'IND', 'numcode' => '356', 'phone_code' => '+91'),


            // Records 100-199 (Indonesia to Spain)

            array('flag'=>urlFlag('id'),'code' => 'ID', 'name' => trans('modules/geocodes/countries/seeders.Indonesia'), 'code2' => 'IDN', 'numcode' => '360', 'phone_code' => '+62'),
            array('flag'=>urlFlag('ir'),'code' => 'IR', 'name' => trans('modules/geocodes/countries/seeders.Iran, Islamic Republic of'), 'code2' => 'IRN', 'numcode' => '364', 'phone_code' => '+98'),
            array('flag'=>urlFlag('iq'),'code' => 'IQ', 'name' => trans('modules/geocodes/countries/seeders.Iraq'), 'code2' => 'IRQ', 'numcode' => '368', 'phone_code' => '+964'),
            array('flag'=>urlFlag('ie'),'code' => 'IE', 'name' => trans('modules/geocodes/countries/seeders.Ireland'), 'code2' => 'IRL', 'numcode' => '372', 'phone_code' => '+353'),
            array('flag'=>urlFlag('il'),'code' => 'IL', 'name' => trans('modules/geocodes/countries/seeders.Israel'), 'code2' => 'ISR', 'numcode' => '376', 'phone_code' => '+972'),
            array('flag'=>urlFlag('it'),'code' => 'IT', 'name' => trans('modules/geocodes/countries/seeders.Italy'), 'code2' => 'ITA', 'numcode' => '380', 'phone_code' => '+39'),
            array('flag'=>urlFlag('jm'),'code' => 'JM', 'name' => trans('modules/geocodes/countries/seeders.Jamaica'), 'code2' => 'JAM', 'numcode' => '388', 'phone_code' => '+1876'),
            array('flag'=>urlFlag('jp'),'code' => 'JP', 'name' => trans('modules/geocodes/countries/seeders.Japan'), 'code2' => 'JPN', 'numcode' => '392', 'phone_code' => '+81'),
            array('flag'=>urlFlag('jo'),'code' => 'JO', 'name' => trans('modules/geocodes/countries/seeders.Jordan'), 'code2' => 'JOR', 'numcode' => '400', 'phone_code' => '+962'),
            array('flag'=>urlFlag('kz'),'code' => 'KZ', 'name' => trans('modules/geocodes/countries/seeders.Kazakhstan'), 'code2' => 'KAZ', 'numcode' => '398', 'phone_code' => '+7'),
            array('flag'=>urlFlag('ke'),'code' => 'KE', 'name' => trans('modules/geocodes/countries/seeders.Kenya'), 'code2' => 'KEN', 'numcode' => '404', 'phone_code' => '+254'),
            array('flag'=>urlFlag('ki'),'code' => 'KI', 'name' => trans('modules/geocodes/countries/seeders.Kiribati'), 'code2' => 'KIR', 'numcode' => '296', 'phone_code' => '+686'),
            array('flag'=>urlFlag('kp'),'code' => 'KP', 'name' => trans('modules/geocodes/countries/seeders.Korea, Democratic People\'s Republic of'), 'code2' => 'PRK', 'numcode' => '408', 'phone_code' => '+850'),
            array('flag'=>urlFlag('kr'),'code' => 'KR', 'name' => trans('modules/geocodes/countries/seeders.Korea, Republic of'), 'code2' => 'KOR', 'numcode' => '410', 'phone_code' => '+82'),
            array('flag'=>urlFlag('kw'),'code' => 'KW', 'name' => trans('modules/geocodes/countries/seeders.Kuwait'), 'code2' => 'KWT', 'numcode' => '414', 'phone_code' => '+965'),
            array('flag'=>urlFlag('kg'),'code' => 'KG', 'name' => trans('modules/geocodes/countries/seeders.Kyrgyzstan'), 'code2' => 'KGZ', 'numcode' => '417', 'phone_code' => '+996'),
            array('flag'=>urlFlag('la'),'code' => 'LA', 'name' => trans('modules/geocodes/countries/seeders.Lao People\'s Democratic Republic'), 'code2' => 'LAO', 'numcode' => '418', 'phone_code' => '+856'),
            array('flag'=>urlFlag('lv'),'code' => 'LV', 'name' => trans('modules/geocodes/countries/seeders.Latvia'), 'code2' => 'LVA', 'numcode' => '428', 'phone_code' => '+371'),
            array('flag'=>urlFlag('lb'),'code' => 'LB', 'name' => trans('modules/geocodes/countries/seeders.Lebanon'), 'code2' => 'LBN', 'numcode' => '422', 'phone_code' => '+961'),
            array('flag'=>urlFlag('ls'),'code' => 'LS', 'name' => trans('modules/geocodes/countries/seeders.Lesotho'), 'code2' => 'LSO', 'numcode' => '426', 'phone_code' => '+266'),
            array('flag'=>urlFlag('lr'),'code' => 'LR', 'name' => trans('modules/geocodes/countries/seeders.Liberia'), 'code2' => 'LBR', 'numcode' => '430', 'phone_code' => '+231'),
            array('flag'=>urlFlag('ly'),'code' => 'LY', 'name' => trans('modules/geocodes/countries/seeders.Libyan Arab Jamahiriya'), 'code2' => 'LBY', 'numcode' => '434', 'phone_code' => '+218'),
            array('flag'=>urlFlag('li'),'code' => 'LI', 'name' => trans('modules/geocodes/countries/seeders.Liechtenstein'), 'code2' => 'LIE', 'numcode' => '438', 'phone_code' => '+423'),
            array('flag'=>urlFlag('lt'),'code' => 'LT', 'name' => trans('modules/geocodes/countries/seeders.Lithuania'), 'code2' => 'LTU', 'numcode' => '440', 'phone_code' => '+370'),
            array('flag'=>urlFlag('lu'),'code' => 'LU', 'name' => trans('modules/geocodes/countries/seeders.Luxembourg'), 'code2' => 'LUX', 'numcode' => '442', 'phone_code' => '+352'),
            array('flag'=>urlFlag('mo'),'code' => 'MO', 'name' => trans('modules/geocodes/countries/seeders.Macao'), 'code2' => 'MAC', 'numcode' => '446', 'phone_code' => '+853'),
            array('flag'=>urlFlag('mk'),'code' => 'MK', 'name' => trans('modules/geocodes/countries/seeders.Macedonia, the Former Yugoslav Republic of'), 'code2' => 'MKD', 'numcode' => '807', 'phone_code' => '+389'),
            array('flag'=>urlFlag('mg'),'code' => 'MG', 'name' => trans('modules/geocodes/countries/seeders.Madagascar'), 'code2' => 'MDG', 'numcode' => '450', 'phone_code' => '+261'),
            array('flag'=>urlFlag('mw'),'code' => 'MW', 'name' => trans('modules/geocodes/countries/seeders.Malawi'), 'code2' => 'MWI', 'numcode' => '454', 'phone_code' => '+265'),
            array('flag'=>urlFlag('my'),'code' => 'MY', 'name' => trans('modules/geocodes/countries/seeders.Malaysia'), 'code2' => 'MYS', 'numcode' => '458', 'phone_code' => '+60'),
            array('flag'=>urlFlag('mv'),'code' => 'MV', 'name' => trans('modules/geocodes/countries/seeders.Maldives'), 'code2' => 'MDV', 'numcode' => '462', 'phone_code' => '+960'),
            array('flag'=>urlFlag('ml'),'code' => 'ML', 'name' => trans('modules/geocodes/countries/seeders.Mali'), 'code2' => 'MLI', 'numcode' => '466', 'phone_code' => '+223'),
            array('flag'=>urlFlag('mt'),'code' => 'MT', 'name' => trans('modules/geocodes/countries/seeders.Malta'), 'code2' => 'MLT', 'numcode' => '470', 'phone_code' => '+356'),
            array('flag'=>urlFlag('mh'),'code' => 'MH', 'name' => trans('modules/geocodes/countries/seeders.Marshall Islands'), 'code2' => 'MHL', 'numcode' => '584', 'phone_code' => '+692'),
            array('flag'=>urlFlag('mq'),'code' => 'MQ', 'name' => trans('modules/geocodes/countries/seeders.Martinique'), 'code2' => 'MTQ', 'numcode' => '474', 'phone_code' => '+596'),
            array('flag'=>urlFlag('mr'),'code' => 'MR', 'name' => trans('modules/geocodes/countries/seeders.Mauritania'), 'code2' => 'MRT', 'numcode' => '478', 'phone_code' => '+222'),
            array('flag'=>urlFlag('mu'),'code' => 'MU', 'name' => trans('modules/geocodes/countries/seeders.Mauritius'), 'code2' => 'MUS', 'numcode' => '480', 'phone_code' => '+230'),
            array('flag'=>urlFlag('yt'),'code' => 'YT', 'name' => trans('modules/geocodes/countries/seeders.Mayotte'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+269'),
            array('flag'=>urlFlag('mx'),'code' => 'MX', 'name' => trans('modules/geocodes/countries/seeders.Mexico'), 'code2' => 'MEX', 'numcode' => '484', 'phone_code' => '+52'),
            array('flag'=>urlFlag('fm'),'code' => 'FM', 'name' => trans('modules/geocodes/countries/seeders.Micronesia, Federated States of'), 'code2' => 'FSM', 'numcode' => '583', 'phone_code' => '+691'),
            array('flag'=>urlFlag('md'),'code' => 'MD', 'name' => trans('modules/geocodes/countries/seeders.Moldova, Republic of'), 'code2' => 'MDA', 'numcode' => '498', 'phone_code' => '+373'),
            array('flag'=>urlFlag('mc'),'code' => 'MC', 'name' => trans('modules/geocodes/countries/seeders.Monaco'), 'code2' => 'MCO', 'numcode' => '492', 'phone_code' => '+377'),
            array('flag'=>urlFlag('mn'),'code' => 'MN', 'name' => trans('modules/geocodes/countries/seeders.Mongolia'), 'code2' => 'MNG', 'numcode' => '496', 'phone_code' => '+976'),
            array('flag'=>urlFlag('ms'),'code' => 'MS', 'name' => trans('modules/geocodes/countries/seeders.Montserrat'), 'code2' => 'MSR', 'numcode' => '500', 'phone_code' => '+1664'),
            array('flag'=>urlFlag('ma'),'code' => 'MA', 'name' => trans('modules/geocodes/countries/seeders.Morocco'), 'code2' => 'MAR', 'numcode' => '504', 'phone_code' => '+212'),
            array('flag'=>urlFlag('mz'),'code' => 'MZ', 'name' => trans('modules/geocodes/countries/seeders.Mozambique'), 'code2' => 'MOZ', 'numcode' => '508', 'phone_code' => '+258'),
            array('flag'=>urlFlag('mm'),'code' => 'MM', 'name' => trans('modules/geocodes/countries/seeders.Myanmar'), 'code2' => 'MMR', 'numcode' => '104', 'phone_code' => '+95'),
            array('flag'=>urlFlag('na'),'code' => 'NA', 'name' => trans('modules/geocodes/countries/seeders.Namibia'), 'code2' => 'NAM', 'numcode' => '516', 'phone_code' => '+264'),
            array('flag'=>urlFlag('nr'),'code' => 'NR', 'name' => trans('modules/geocodes/countries/seeders.Nauru'), 'code2' => 'NRU', 'numcode' => '520', 'phone_code' => '+674'),
            array('flag'=>urlFlag('np'),'code' => 'NP', 'name' => trans('modules/geocodes/countries/seeders.Nepal'), 'code2' => 'NPL', 'numcode' => '524', 'phone_code' => '+977'),
            array('flag'=>urlFlag('nl'),'code' => 'NL', 'name' => trans('modules/geocodes/countries/seeders.Netherlands'), 'code2' => 'NLD', 'numcode' => '528', 'phone_code' => '+31'),
            array('flag'=>urlFlag('an'),'code' => 'AN', 'name' => trans('modules/geocodes/countries/seeders.Netherlands Antilles'), 'code2' => 'ANT', 'numcode' => '530', 'phone_code' => '+599'),
            array('flag'=>urlFlag('nc'),'code' => 'NC', 'name' => trans('modules/geocodes/countries/seeders.New Caledonia'), 'code2' => 'NCL', 'numcode' => '540', 'phone_code' => '+687'),
            array('flag'=>urlFlag('nz'),'code' => 'NZ', 'name' => trans('modules/geocodes/countries/seeders.New Zealand'), 'code2' => 'NZL', 'numcode' => '554', 'phone_code' => '+64'),
            array('flag'=>urlFlag('ni'),'code' => 'NI', 'name' => trans('modules/geocodes/countries/seeders.Nicaragua'), 'code2' => 'NIC', 'numcode' => '558', 'phone_code' => '+505'),
            array('flag'=>urlFlag('ne'),'code' => 'NE', 'name' => trans('modules/geocodes/countries/seeders.Niger'), 'code2' => 'NER', 'numcode' => '562', 'phone_code' => '+227'),
            array('flag'=>urlFlag('ng'),'code' => 'NG', 'name' => trans('modules/geocodes/countries/seeders.Nigeria'), 'code2' => 'NGA', 'numcode' => '566', 'phone_code' => '+234'),
            array('flag'=>urlFlag('nu'),'code' => 'NU', 'name' => trans('modules/geocodes/countries/seeders.Niue'), 'code2' => 'NIU', 'numcode' => '570', 'phone_code' => '+683'),
            array('flag'=>urlFlag('nf'),'code' => 'NF', 'name' => trans('modules/geocodes/countries/seeders.Norfolk Island'), 'code2' => 'NFK', 'numcode' => '574', 'phone_code' => '+672'),
            array('flag'=>urlFlag('mp'),'code' => 'MP', 'name' => trans('modules/geocodes/countries/seeders.Northern Mariana Islands'), 'code2' => 'MNP', 'numcode' => '580', 'phone_code' => '+1670'),
            array('flag'=>urlFlag('no'),'code' => 'NO', 'name' => trans('modules/geocodes/countries/seeders.Norway'), 'code2' => 'NOR', 'numcode' => '578', 'phone_code' => '+47'),
            array('flag'=>urlFlag('om'),'code' => 'OM', 'name' => trans('modules/geocodes/countries/seeders.Oman'), 'code2' => 'OMN', 'numcode' => '512', 'phone_code' => '+968'),
            array('flag'=>urlFlag('pk'),'code' => 'PK', 'name' => trans('modules/geocodes/countries/seeders.Pakistan'), 'code2' => 'PAK', 'numcode' => '586', 'phone_code' => '+92'),
            array('flag'=>urlFlag('pw'),'code' => 'PW', 'name' => trans('modules/geocodes/countries/seeders.Palau'), 'code2' => 'PLW', 'numcode' => '585', 'phone_code' => '+680'),
            array('flag'=>urlFlag('ps'),'code' => 'PS', 'name' => trans('modules/geocodes/countries/seeders.Palestinian Territory, Occupied'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+970'),
            array('flag'=>urlFlag('pa'),'code' => 'PA', 'name' => trans('modules/geocodes/countries/seeders.Panama'), 'code2' => 'PAN', 'numcode' => '591', 'phone_code' => '+507'),
            array('flag'=>urlFlag('pg'),'code' => 'PG', 'name' => trans('modules/geocodes/countries/seeders.Papua New Guinea'), 'code2' => 'PNG', 'numcode' => '598', 'phone_code' => '+675'),
            array('flag'=>urlFlag('py'),'code' => 'PY', 'name' => trans('modules/geocodes/countries/seeders.Paraguay'), 'code2' => 'PRY', 'numcode' => '600', 'phone_code' => '+595'),
            array('flag'=>urlFlag('pe'),'code' => 'PE', 'name' => trans('modules/geocodes/countries/seeders.Peru'), 'code2' => 'PER', 'numcode' => '604', 'phone_code' => '+51'),
            array('flag'=>urlFlag('ph'),'code' => 'PH', 'name' => trans('modules/geocodes/countries/seeders.Philippines'), 'code2' => 'PHL', 'numcode' => '608', 'phone_code' => '+63'),
            array('flag'=>urlFlag('pn'),'code' => 'PN', 'name' => trans('modules/geocodes/countries/seeders.Pitcairn'), 'code2' => 'PCN', 'numcode' => '612', 'phone_code' => '+0'),
            array('flag'=>urlFlag('pl'),'code' => 'PL', 'name' => trans('modules/geocodes/countries/seeders.Poland'), 'code2' => 'POL', 'numcode' => '616', 'phone_code' => '+48'),
            array('flag'=>urlFlag('pt'),'code' => 'PT', 'name' => trans('modules/geocodes/countries/seeders.Portugal'), 'code2' => 'PRT', 'numcode' => '620', 'phone_code' => '+351'),
            array('flag'=>urlFlag('pr'),'code' => 'PR', 'name' => trans('modules/geocodes/countries/seeders.Puerto Rico'), 'code2' => 'PRI', 'numcode' => '630', 'phone_code' => '+1787'),
            array('flag'=>urlFlag('qa'),'code' => 'QA', 'name' => trans('modules/geocodes/countries/seeders.Qatar'), 'code2' => 'QAT', 'numcode' => '634', 'phone_code' => '+974'),
            array('flag'=>urlFlag('re'),'code' => 'RE', 'name' => trans('modules/geocodes/countries/seeders.Reunion'), 'code2' => 'REU', 'numcode' => '638', 'phone_code' => '+262'),
            array('flag'=>urlFlag('ro'),'code' => 'RO', 'name' => trans('modules/geocodes/countries/seeders.Romania'), 'code2' => 'ROM', 'numcode' => '642', 'phone_code' => '+40'),
            array('flag'=>urlFlag('ru'),'code' => 'RU', 'name' => trans('modules/geocodes/countries/seeders.Russian Federation'), 'code2' => 'RUS', 'numcode' => '643', 'phone_code' => '+70'),
            array('flag'=>urlFlag('rw'),'code' => 'RW', 'name' => trans('modules/geocodes/countries/seeders.Rwanda'), 'code2' => 'RWA', 'numcode' => '646', 'phone_code' => '+250'),
            array('flag'=>urlFlag('sh'),'code' => 'SH', 'name' => trans('modules/geocodes/countries/seeders.Saint Helena'), 'code2' => 'SHN', 'numcode' => '654', 'phone_code' => '+290'),
            array('flag'=>urlFlag('kn'),'code' => 'KN', 'name' => trans('modules/geocodes/countries/seeders.Saint Kitts and Nevis'), 'code2' => 'KNA', 'numcode' => '659', 'phone_code' => '+1869'),
            array('flag'=>urlFlag('lc'),'code' => 'LC', 'name' => trans('modules/geocodes/countries/seeders.Saint Lucia'), 'code2' => 'LCA', 'numcode' => '662', 'phone_code' => '+1758'),
            array('flag'=>urlFlag('pm'),'code' => 'PM', 'name' => trans('modules/geocodes/countries/seeders.Saint Pierre and Miquelon'), 'code2' => 'SPM', 'numcode' => '666', 'phone_code' => '+508'),
            array('flag'=>urlFlag('vc'),'code' => 'VC', 'name' => trans('modules/geocodes/countries/seeders.Saint Vincent and the Grenadines'), 'code2' => 'VCT', 'numcode' => '670', 'phone_code' => '+1784'),
            array('flag'=>urlFlag('ws'),'code' => 'WS', 'name' => trans('modules/geocodes/countries/seeders.Samoa'), 'code2' => 'WSM', 'numcode' => '882', 'phone_code' => '+684'),
            array('flag'=>urlFlag('sm'),'code' => 'SM', 'name' => trans('modules/geocodes/countries/seeders.San Marino'), 'code2' => 'SMR', 'numcode' => '674', 'phone_code' => '+378'),
            array('flag'=>urlFlag('st'),'code' => 'ST', 'name' => trans('modules/geocodes/countries/seeders.Sao Tome and Principe'), 'code2' => 'STP', 'numcode' => '678', 'phone_code' => '+239'),
            array('flag'=>urlFlag('sa'),'code' => 'SA', 'name' => trans('modules/geocodes/countries/seeders.Saudi Arabia'), 'code2' => 'SAU', 'numcode' => '682', 'phone_code' => '+966'),
            array('flag'=>urlFlag('sn'),'code' => 'SN', 'name' => trans('modules/geocodes/countries/seeders.Senegal'), 'code2' => 'SEN', 'numcode' => '686', 'phone_code' => '+221'),
            array('flag'=>urlFlag('cs'),'code' => 'CS', 'name' => trans('modules/geocodes/countries/seeders.Serbia and Montenegro'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+381'),
            array('flag'=>urlFlag('sc'),'code' => 'SC', 'name' => trans('modules/geocodes/countries/seeders.Seychelles'), 'code2' => 'SYC', 'numcode' => '690', 'phone_code' => '+248'),
            array('flag'=>urlFlag('sl'),'code' => 'SL', 'name' => trans('modules/geocodes/countries/seeders.Sierra Leone'), 'code2' => 'SLE', 'numcode' => '694', 'phone_code' => '+232'),
            array('flag'=>urlFlag('sg'),'code' => 'SG', 'name' => trans('modules/geocodes/countries/seeders.Singapore'), 'code2' => 'SGP', 'numcode' => '702', 'phone_code' => '+65'),
            array('flag'=>urlFlag('sk'),'code' => 'SK', 'name' => trans('modules/geocodes/countries/seeders.Slovakia'), 'code2' => 'SVK', 'numcode' => '703', 'phone_code' => '+421'),
            array('flag'=>urlFlag('si'),'code' => 'SI', 'name' => trans('modules/geocodes/countries/seeders.Slovenia'), 'code2' => 'SVN', 'numcode' => '705', 'phone_code' => '+386'),
            array('flag'=>urlFlag('sb'),'code' => 'SB', 'name' => trans('modules/geocodes/countries/seeders.Solomon Islands'), 'code2' => 'SLB', 'numcode' => '90', 'phone_code' => '+677'),
            array('flag'=>urlFlag('so'),'code' => 'SO', 'name' => trans('modules/geocodes/countries/seeders.Somalia'), 'code2' => 'SOM', 'numcode' => '706', 'phone_code' => '+252'),
            array('flag'=>urlFlag('za'),'code' => 'ZA', 'name' => trans('modules/geocodes/countries/seeders.South Africa'), 'code2' => 'ZAF', 'numcode' => '710', 'phone_code' => '+27'),
            array('flag'=>urlFlag('gs'),'code' => 'GS', 'name' => trans('modules/geocodes/countries/seeders.South Georgia and the South Sandwich Islands'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+0'),
            array('flag'=>urlFlag('es'),'code' => 'ES', 'name' => trans('modules/geocodes/countries/seeders.Spain'), 'code2' => 'ESP', 'numcode' => '724', 'phone_code' => '+34'),


            // Records 200-253 (Sri Lanka to South Sudan)

            array('flag'=>urlFlag('lk'),'code' => 'LK', 'name' => trans('modules/geocodes/countries/seeders.Sri Lanka'), 'code2' => 'LKA', 'numcode' => '144', 'phone_code' => '+94'),
            array('flag'=>urlFlag('sd'),'code' => 'SD', 'name' => trans('modules/geocodes/countries/seeders.Sudan'), 'code2' => 'SDN', 'numcode' => '736', 'phone_code' => '+249'),
            array('flag'=>urlFlag('sr'),'code' => 'SR', 'name' => trans('modules/geocodes/countries/seeders.Suriname'), 'code2' => 'SUR', 'numcode' => '740', 'phone_code' => '+597'),
            array('flag'=>urlFlag('sj'),'code' => 'SJ', 'name' => trans('modules/geocodes/countries/seeders.Svalbard and Jan Mayen'), 'code2' => 'SJM', 'numcode' => '744', 'phone_code' => '+47'),
            array('flag'=>urlFlag('sz'),'code' => 'SZ', 'name' => trans('modules/geocodes/countries/seeders.Swaziland'), 'code2' => 'SWZ', 'numcode' => '748', 'phone_code' => '+268'),
            array('flag'=>urlFlag('se'),'code' => 'SE', 'name' => trans('modules/geocodes/countries/seeders.Sweden'), 'code2' => 'SWE', 'numcode' => '752', 'phone_code' => '+46'),
            array('flag'=>urlFlag('ch'),'code' => 'CH', 'name' => trans('modules/geocodes/countries/seeders.Switzerland'), 'code2' => 'CHE', 'numcode' => '756', 'phone_code' => '+41'),
            array('flag'=>urlFlag('sy'),'code' => 'SY', 'name' => trans('modules/geocodes/countries/seeders.Syrian Arab Republic'), 'code2' => 'SYR', 'numcode' => '760', 'phone_code' => '+963'),
            array('flag'=>urlFlag('tw'),'code' => 'TW', 'name' => trans('modules/geocodes/countries/seeders.Taiwan, Province of China'), 'code2' => 'TWN', 'numcode' => '158', 'phone_code' => '+886'),
            array('flag'=>urlFlag('tj'),'code' => 'TJ', 'name' => trans('modules/geocodes/countries/seeders.Tajikistan'), 'code2' => 'TJK', 'numcode' => '762', 'phone_code' => '+992'),
            array('flag'=>urlFlag('tz'),'code' => 'TZ', 'name' => trans('modules/geocodes/countries/seeders.Tanzania, United Republic of'), 'code2' => 'TZA', 'numcode' => '834', 'phone_code' => '+255'),
            array('flag'=>urlFlag('th'),'code' => 'TH', 'name' => trans('modules/geocodes/countries/seeders.Thailand'), 'code2' => 'THA', 'numcode' => '764', 'phone_code' => '+66'),
            array('flag'=>urlFlag('tl'),'code' => 'TL', 'name' => trans('modules/geocodes/countries/seeders.Timor-Leste'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+670'),
            array('flag'=>urlFlag('tg'),'code' => 'TG', 'name' => trans('modules/geocodes/countries/seeders.Togo'), 'code2' => 'TGO', 'numcode' => '768', 'phone_code' => '+228'),
            array('flag'=>urlFlag('tk'),'code' => 'TK', 'name' => trans('modules/geocodes/countries/seeders.Tokelau'), 'code2' => 'TKL', 'numcode' => '772', 'phone_code' => '+690'),
            array('flag'=>urlFlag('to'),'code' => 'TO', 'name' => trans('modules/geocodes/countries/seeders.Tonga'), 'code2' => 'TON', 'numcode' => '776', 'phone_code' => '+676'),
            array('flag'=>urlFlag('tt'),'code' => 'TT', 'name' => trans('modules/geocodes/countries/seeders.Trinidad and Tobago'), 'code2' => 'TTO', 'numcode' => '780', 'phone_code' => '+1868'),
            array('flag'=>urlFlag('tn'),'code' => 'TN', 'name' => trans('modules/geocodes/countries/seeders.Tunisia'), 'code2' => 'TUN', 'numcode' => '788', 'phone_code' => '+216'),
            array('flag'=>urlFlag('tr'),'code' => 'TR', 'name' => trans('modules/geocodes/countries/seeders.Turkey'), 'code2' => 'TUR', 'numcode' => '792', 'phone_code' => '+90'),
            array('flag'=>urlFlag('tm'),'code' => 'TM', 'name' => trans('modules/geocodes/countries/seeders.Turkmenistan'), 'code2' => 'TKM', 'numcode' => '795', 'phone_code' => '+7370'),
            array('flag'=>urlFlag('tc'),'code' => 'TC', 'name' => trans('modules/geocodes/countries/seeders.Turks and Caicos Islands'), 'code2' => 'TCA', 'numcode' => '796', 'phone_code' => '+1649'),
            array('flag'=>urlFlag('tv'),'code' => 'TV', 'name' => trans('modules/geocodes/countries/seeders.Tuvalu'), 'code2' => 'TUV', 'numcode' => '798', 'phone_code' => '+688'),
            array('flag'=>urlFlag('ug'),'code' => 'UG', 'name' => trans('modules/geocodes/countries/seeders.Uganda'), 'code2' => 'UGA', 'numcode' => '800', 'phone_code' => '+256'),
            array('flag'=>urlFlag('ua'),'code' => 'UA', 'name' => trans('modules/geocodes/countries/seeders.Ukraine'), 'code2' => 'UKR', 'numcode' => '804', 'phone_code' => '+380'),
            array('flag'=>urlFlag('ae'),'code' => 'AE', 'name' => trans('modules/geocodes/countries/seeders.United Arab Emirates'), 'code2' => 'ARE', 'numcode' => '784', 'phone_code' => '+971'),
            array('flag'=>urlFlag('gb'),'code' => 'GB', 'name' => trans('modules/geocodes/countries/seeders.United Kingdom'), 'code2' => 'GBR', 'numcode' => '826', 'phone_code' => '+44'),
            array('flag'=>urlFlag('us'),'code' => 'US', 'name' => trans('modules/geocodes/countries/seeders.United States'), 'code2' => 'USA', 'numcode' => '840', 'phone_code' => '+1'),
            array('flag'=>urlFlag('um'),'code' => 'UM', 'name' => trans('modules/geocodes/countries/seeders.United States Minor Outlying Islands'), 'code2' => NULL,'numcode' => NULL,'phone_code' => '+1'),
            array('flag'=>urlFlag('uy'),'code' => 'UY', 'name' => trans('modules/geocodes/countries/seeders.Uruguay'), 'code2' => 'URY', 'numcode' => '858', 'phone_code' => '+598'),
            array('flag'=>urlFlag('uz'),'code' => 'UZ', 'name' => trans('modules/geocodes/countries/seeders.Uzbekistan'), 'code2' => 'UZB', 'numcode' => '860', 'phone_code' => '+998'),
            array('flag'=>urlFlag('vu'),'code' => 'VU', 'name' => trans('modules/geocodes/countries/seeders.Vanuatu'), 'code2' => 'VUT', 'numcode' => '548', 'phone_code' => '+678'),
            array('flag'=>urlFlag('ve'),'code' => 'VE', 'name' => trans('modules/geocodes/countries/seeders.Venezuela'), 'code2' => 'VEN', 'numcode' => '862', 'phone_code' => '+58'),
            array('flag'=>urlFlag('vn'),'code' => 'VN', 'name' => trans('modules/geocodes/countries/seeders.Viet Nam'), 'code2' => 'VNM', 'numcode' => '704', 'phone_code' => '+84'),
            array('flag'=>urlFlag('vg'),'code' => 'VG', 'name' => trans('modules/geocodes/countries/seeders.Virgin Islands, British'), 'code2' => 'VGB', 'numcode' => '92', 'phone_code' => '+1284'),
            array('flag'=>urlFlag('vi'),'code' => 'VI', 'name' => trans('modules/geocodes/countries/seeders.Virgin Islands, U.S.'), 'code2' => 'VIR', 'numcode' => '850', 'phone_code' => '+1340'),
            array('flag'=>urlFlag('wf'),'code' => 'WF', 'name' => trans('modules/geocodes/countries/seeders.Wallis and Futuna'), 'code2' => 'WLF', 'numcode' => '876', 'phone_code' => '+681'),
            array('flag'=>urlFlag('eh'),'code' => 'EH', 'name' => trans('modules/geocodes/countries/seeders.Western Sahara'), 'code2' => 'ESH', 'numcode' => '732', 'phone_code' => '+212'),
            array('flag'=>urlFlag('ye'),'code' => 'YE', 'name' => trans('modules/geocodes/countries/seeders.Yemen'), 'code2' => 'YEM', 'numcode' => '887', 'phone_code' => '+967'),
            array('flag'=>urlFlag('zm'),'code' => 'ZM', 'name' => trans('modules/geocodes/countries/seeders.Zambia'), 'code2' => 'ZMB', 'numcode' => '894', 'phone_code' => '+260'),
            array('flag'=>urlFlag('zw'),'code' => 'ZW', 'name' => trans('modules/geocodes/countries/seeders.Zimbabwe'), 'code2' => 'ZWE', 'numcode' => '716', 'phone_code' => '+263'),
            array('flag'=>urlFlag('rs'),'code' => 'RS', 'name' => trans('modules/geocodes/countries/seeders.Serbia'), 'code2' => 'SRB', 'numcode' => '688', 'phone_code' => '+381'),
            array('flag'=>urlFlag('ap'),'code' => 'AP', 'name' => trans('modules/geocodes/countries/seeders.Asia / Pacific Region'), 'code2' => '0', 'numcode' => '0', 'phone_code' => '+0'),
            array('flag'=>urlFlag('me'),'code' => 'ME', 'name' => trans('modules/geocodes/countries/seeders.Montenegro'), 'code2' => 'MNE', 'numcode' => '499', 'phone_code' => '+382'),
            array('flag'=>urlFlag('az'),'code' => 'AX', 'name' => trans('modules/geocodes/countries/seeders.Aland Islands'), 'code2' => 'ALA', 'numcode' => '248', 'phone_code' => '+358'),
            array('flag'=>urlFlag('bq'),'code' => 'BQ', 'name' => trans('modules/geocodes/countries/seeders.Bonaire, Sint Eustatius and Saba'), 'code2' => 'BES', 'numcode' => '535', 'phone_code' => '+599'),
            array('flag'=>urlFlag('cw'),'code' => 'CW', 'name' => trans('modules/geocodes/countries/seeders.Curacao'), 'code2' => 'CUW', 'numcode' => '531', 'phone_code' => '+599'),
            array('flag'=>urlFlag('gg'),'code' => 'GG', 'name' => trans('modules/geocodes/countries/seeders.Guernsey'), 'code2' => 'GGY', 'numcode' => '831', 'phone_code' => '+44'),
            array('flag'=>urlFlag('im'),'code' => 'IM', 'name' => trans('modules/geocodes/countries/seeders.Isle of Man'), 'code2' => 'IMN', 'numcode' => '833', 'phone_code' => '+44'),
            array('flag'=>urlFlag('je'),'code' => 'JE', 'name' => trans('modules/geocodes/countries/seeders.Jersey'), 'code2' => 'JEY', 'numcode' => '832', 'phone_code' => '+44'),
            array('flag'=>urlFlag('xk'),'code' => 'XK', 'name' => trans('modules/geocodes/countries/seeders.Kosovo'), 'code2' => '---', 'numcode' => '0', 'phone_code' => '+381'),
            array('flag'=>urlFlag('bl'),'code' => 'BL', 'name' => trans('modules/geocodes/countries/seeders.Saint Barthelemy'), 'code2' => 'BLM', 'numcode' => '652', 'phone_code' => '+590'),
            array('flag'=>urlFlag('mf'),'code' => 'MF', 'name' => trans('modules/geocodes/countries/seeders.Saint Martin'), 'code2' => 'MAF', 'numcode' => '663', 'phone_code' => '+590'),
            array('flag'=>urlFlag('sx'),'code' => 'SX', 'name' => trans('modules/geocodes/countries/seeders.Sint Maarten'), 'code2' => 'SXM', 'numcode' => '534', 'phone_code' => '+1'),
            array('flag'=>urlFlag('ss'),'code' => 'SS', 'name' => trans('modules/geocodes/countries/seeders.South Sudan'), 'code2' => 'SSD', 'numcode' => '728', 'phone_code' => '+211')
          );

          DB::table('countries')->insert($countries);


    }
}
